version: "3.8"

services:
  api:
    build: .
    container_name: product-api
    depends_on:
      - db
      - popdb
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: productsdb
    networks:
      - upb
    #Ya no exponemos 3000
    # ports:
    #   - "3000:3000"

  db:
    image: postgres:15
    container_name: product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productsdb
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - upb

  popdb:
    build: .
    command: ["node", "popdb.js"]
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: productsdb
    networks:
      - upb

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - upb

  nginx:
    build:
      context: ./nginx
    container_name: reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - upb

volumes:
  dbdata:

networks:
  upb:
